WORKFLOW_ORDER = (
    "analyze_intent",
    "build_search_strategy",
    "retrieve_expert_signals",
    "generate_candidates",
    "retrieve_products",
    "filter_evidence",
    "summarize_results",
    "generate_recommendation",
)

DEFAULT_PRODUCT_LIMIT = 5

MECHANICAL_KEYBOARD_REFERENCE_CANDIDATES = (
    {
        "candidate_id": "mk-keymellow-75-flex",
        "name": "KeyMellow 75 Flex",
        "brand": "KeyMellow",
        "reference_price": 149000,
        "layout": "75%",
        "switch_type": "silent_tactile",
        "noise_level": "quiet",
        "beginner_friendly": True,
        "aliases": ("keymellow 75 flex", "keymellow", "75 flex"),
    },
    {
        "candidate_id": "mk-lumakeys-flow-tkl",
        "name": "LumaKeys Flow TKL",
        "brand": "LumaKeys",
        "reference_price": 129000,
        "layout": "TKL",
        "switch_type": "silent_linear",
        "noise_level": "quiet",
        "beginner_friendly": True,
        "aliases": ("lumakeys flow tkl", "lumakeys", "flow tkl"),
    },
    {
        "candidate_id": "mk-monotype-office-98",
        "name": "MonoType Office 98",
        "brand": "MonoType",
        "reference_price": 139000,
        "layout": "full_size",
        "switch_type": "silent_tactile",
        "noise_level": "quiet",
        "beginner_friendly": True,
        "aliases": ("monotype office 98", "monotype", "office 98"),
    },
    {
        "candidate_id": "mk-clickforge-rgb-pro",
        "name": "ClickForge RGB Pro",
        "brand": "ClickForge",
        "reference_price": 99000,
        "layout": "TKL",
        "switch_type": "clicky",
        "noise_level": "loud",
        "beginner_friendly": False,
        "aliases": ("clickforge rgb pro", "clickforge", "rgb pro"),
    },
    {
        "candidate_id": "mk-atelier-loop-75",
        "name": "Atelier Loop 75",
        "brand": "Atelier",
        "reference_price": 169000,
        "layout": "75%",
        "switch_type": "silent_linear",
        "noise_level": "quiet",
        "beginner_friendly": True,
        "aliases": ("atelier loop 75", "atelier", "loop 75"),
    },
)
